/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsNeedsVsWantsRouteImport } from './routes/lessons.needs-vs-wants'

const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsNeedsVsWantsRoute = LessonsNeedsVsWantsRouteImport.update({
  id: '/needs-vs-wants',
  path: '/needs-vs-wants',
  getParentRoute: () => LessonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/notebook': typeof NotebookRoute
  '/parents': typeof ParentsRoute
  '/lessons/needs-vs-wants': typeof LessonsNeedsVsWantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/notebook': typeof NotebookRoute
  '/parents': typeof ParentsRoute
  '/lessons/needs-vs-wants': typeof LessonsNeedsVsWantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/notebook': typeof NotebookRoute
  '/parents': typeof ParentsRoute
  '/lessons/needs-vs-wants': typeof LessonsNeedsVsWantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/lessons'
    | '/notebook'
    | '/parents'
    | '/lessons/needs-vs-wants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/lessons'
    | '/notebook'
    | '/parents'
    | '/lessons/needs-vs-wants'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/lessons'
    | '/notebook'
    | '/parents'
    | '/lessons/needs-vs-wants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LessonsRoute: typeof LessonsRouteWithChildren
  NotebookRoute: typeof NotebookRoute
  ParentsRoute: typeof ParentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/needs-vs-wants': {
      id: '/lessons/needs-vs-wants'
      path: '/needs-vs-wants'
      fullPath: '/lessons/needs-vs-wants'
      preLoaderRoute: typeof LessonsNeedsVsWantsRouteImport
      parentRoute: typeof LessonsRoute
    }
  }
}

interface LessonsRouteChildren {
  LessonsNeedsVsWantsRoute: typeof LessonsNeedsVsWantsRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsNeedsVsWantsRoute: LessonsNeedsVsWantsRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LessonsRoute: LessonsRouteWithChildren,
  NotebookRoute: NotebookRoute,
  ParentsRoute: ParentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
