/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsWhereMoneyComesFromRouteImport } from './routes/lessons.where-money-comes-from'
import { Route as LessonsWhatIsInflationRouteImport } from './routes/lessons.what-is-inflation'
import { Route as LessonsWhatIsABankRouteImport } from './routes/lessons.what-is-a-bank'
import { Route as LessonsStocksMadeSimpleRouteImport } from './routes/lessons.stocks-made-simple'
import { Route as LessonsSmartOnlineSpendingRouteImport } from './routes/lessons.smart-online-spending'
import { Route as LessonsSharingGivingRouteImport } from './routes/lessons.sharing-giving'
import { Route as LessonsPurposeOfMoneyRouteImport } from './routes/lessons.purpose-of-money'
import { Route as LessonsPiggyBankMagicRouteImport } from './routes/lessons.piggy-bank-magic'
import { Route as LessonsNeedsVsWantsRouteImport } from './routes/lessons.needs-vs-wants'
import { Route as LessonsEarningBeyondPocketMoneyRouteImport } from './routes/lessons.earning-beyond-pocket-money'
import { Route as LessonsCountingCoinsRouteImport } from './routes/lessons.counting-coins'
import { Route as LessonsCompoundInterestRouteImport } from './routes/lessons.compound-interest'
import { Route as LessonsBudgetingLikeABossRouteImport } from './routes/lessons.budgeting-like-a-boss'
import { Route as DashboardParentRouteImport } from './routes/dashboard.parent'
import { Route as DashboardChildRouteImport } from './routes/dashboard.child'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsWhereMoneyComesFromRoute =
  LessonsWhereMoneyComesFromRouteImport.update({
    id: '/where-money-comes-from',
    path: '/where-money-comes-from',
    getParentRoute: () => LessonsRoute,
  } as any)
const LessonsWhatIsInflationRoute = LessonsWhatIsInflationRouteImport.update({
  id: '/what-is-inflation',
  path: '/what-is-inflation',
  getParentRoute: () => LessonsRoute,
} as any)
const LessonsWhatIsABankRoute = LessonsWhatIsABankRouteImport.update({
  id: '/what-is-a-bank',
  path: '/what-is-a-bank',
  getParentRoute: () => LessonsRoute,
} as any)
const LessonsStocksMadeSimpleRoute = LessonsStocksMadeSimpleRouteImport.update({
  id: '/stocks-made-simple',
  path: '/stocks-made-simple',
  getParentRoute: () => LessonsRoute,
} as any)
const LessonsSmartOnlineSpendingRoute =
  LessonsSmartOnlineSpendingRouteImport.update({
    id: '/smart-online-spending',
    path: '/smart-online-spending',
    getParentRoute: () => LessonsRoute,
  } as any)
const LessonsSharingGivingRoute = LessonsSharingGivingRouteImport.update({
  id: '/sharing-giving',
  path: '/sharing-giving',
  getParentRoute: () => LessonsRoute,
} as any)
const LessonsPurposeOfMoneyRoute = LessonsPurposeOfMoneyRouteImport.update({
  id: '/purpose-of-money',
  path: '/purpose-of-money',
  getParentRoute: () => LessonsRoute,
} as any)
const LessonsPiggyBankMagicRoute = LessonsPiggyBankMagicRouteImport.update({
  id: '/piggy-bank-magic',
  path: '/piggy-bank-magic',
  getParentRoute: () => LessonsRoute,
} as any)
const LessonsNeedsVsWantsRoute = LessonsNeedsVsWantsRouteImport.update({
  id: '/needs-vs-wants',
  path: '/needs-vs-wants',
  getParentRoute: () => LessonsRoute,
} as any)
const LessonsEarningBeyondPocketMoneyRoute =
  LessonsEarningBeyondPocketMoneyRouteImport.update({
    id: '/earning-beyond-pocket-money',
    path: '/earning-beyond-pocket-money',
    getParentRoute: () => LessonsRoute,
  } as any)
const LessonsCountingCoinsRoute = LessonsCountingCoinsRouteImport.update({
  id: '/counting-coins',
  path: '/counting-coins',
  getParentRoute: () => LessonsRoute,
} as any)
const LessonsCompoundInterestRoute = LessonsCompoundInterestRouteImport.update({
  id: '/compound-interest',
  path: '/compound-interest',
  getParentRoute: () => LessonsRoute,
} as any)
const LessonsBudgetingLikeABossRoute =
  LessonsBudgetingLikeABossRouteImport.update({
    id: '/budgeting-like-a-boss',
    path: '/budgeting-like-a-boss',
    getParentRoute: () => LessonsRoute,
  } as any)
const DashboardParentRoute = DashboardParentRouteImport.update({
  id: '/dashboard/parent',
  path: '/dashboard/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChildRoute = DashboardChildRouteImport.update({
  id: '/dashboard/child',
  path: '/dashboard/child',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/notebook': typeof NotebookRoute
  '/parents': typeof ParentsRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/dashboard/child': typeof DashboardChildRoute
  '/dashboard/parent': typeof DashboardParentRoute
  '/lessons/budgeting-like-a-boss': typeof LessonsBudgetingLikeABossRoute
  '/lessons/compound-interest': typeof LessonsCompoundInterestRoute
  '/lessons/counting-coins': typeof LessonsCountingCoinsRoute
  '/lessons/earning-beyond-pocket-money': typeof LessonsEarningBeyondPocketMoneyRoute
  '/lessons/needs-vs-wants': typeof LessonsNeedsVsWantsRoute
  '/lessons/piggy-bank-magic': typeof LessonsPiggyBankMagicRoute
  '/lessons/purpose-of-money': typeof LessonsPurposeOfMoneyRoute
  '/lessons/sharing-giving': typeof LessonsSharingGivingRoute
  '/lessons/smart-online-spending': typeof LessonsSmartOnlineSpendingRoute
  '/lessons/stocks-made-simple': typeof LessonsStocksMadeSimpleRoute
  '/lessons/what-is-a-bank': typeof LessonsWhatIsABankRoute
  '/lessons/what-is-inflation': typeof LessonsWhatIsInflationRoute
  '/lessons/where-money-comes-from': typeof LessonsWhereMoneyComesFromRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/notebook': typeof NotebookRoute
  '/parents': typeof ParentsRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/dashboard/child': typeof DashboardChildRoute
  '/dashboard/parent': typeof DashboardParentRoute
  '/lessons/budgeting-like-a-boss': typeof LessonsBudgetingLikeABossRoute
  '/lessons/compound-interest': typeof LessonsCompoundInterestRoute
  '/lessons/counting-coins': typeof LessonsCountingCoinsRoute
  '/lessons/earning-beyond-pocket-money': typeof LessonsEarningBeyondPocketMoneyRoute
  '/lessons/needs-vs-wants': typeof LessonsNeedsVsWantsRoute
  '/lessons/piggy-bank-magic': typeof LessonsPiggyBankMagicRoute
  '/lessons/purpose-of-money': typeof LessonsPurposeOfMoneyRoute
  '/lessons/sharing-giving': typeof LessonsSharingGivingRoute
  '/lessons/smart-online-spending': typeof LessonsSmartOnlineSpendingRoute
  '/lessons/stocks-made-simple': typeof LessonsStocksMadeSimpleRoute
  '/lessons/what-is-a-bank': typeof LessonsWhatIsABankRoute
  '/lessons/what-is-inflation': typeof LessonsWhatIsInflationRoute
  '/lessons/where-money-comes-from': typeof LessonsWhereMoneyComesFromRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/notebook': typeof NotebookRoute
  '/parents': typeof ParentsRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/terms': typeof TermsRoute
  '/dashboard/child': typeof DashboardChildRoute
  '/dashboard/parent': typeof DashboardParentRoute
  '/lessons/budgeting-like-a-boss': typeof LessonsBudgetingLikeABossRoute
  '/lessons/compound-interest': typeof LessonsCompoundInterestRoute
  '/lessons/counting-coins': typeof LessonsCountingCoinsRoute
  '/lessons/earning-beyond-pocket-money': typeof LessonsEarningBeyondPocketMoneyRoute
  '/lessons/needs-vs-wants': typeof LessonsNeedsVsWantsRoute
  '/lessons/piggy-bank-magic': typeof LessonsPiggyBankMagicRoute
  '/lessons/purpose-of-money': typeof LessonsPurposeOfMoneyRoute
  '/lessons/sharing-giving': typeof LessonsSharingGivingRoute
  '/lessons/smart-online-spending': typeof LessonsSmartOnlineSpendingRoute
  '/lessons/stocks-made-simple': typeof LessonsStocksMadeSimpleRoute
  '/lessons/what-is-a-bank': typeof LessonsWhatIsABankRoute
  '/lessons/what-is-inflation': typeof LessonsWhatIsInflationRoute
  '/lessons/where-money-comes-from': typeof LessonsWhereMoneyComesFromRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/lessons'
    | '/notebook'
    | '/parents'
    | '/privacy'
    | '/safety'
    | '/terms'
    | '/dashboard/child'
    | '/dashboard/parent'
    | '/lessons/budgeting-like-a-boss'
    | '/lessons/compound-interest'
    | '/lessons/counting-coins'
    | '/lessons/earning-beyond-pocket-money'
    | '/lessons/needs-vs-wants'
    | '/lessons/piggy-bank-magic'
    | '/lessons/purpose-of-money'
    | '/lessons/sharing-giving'
    | '/lessons/smart-online-spending'
    | '/lessons/stocks-made-simple'
    | '/lessons/what-is-a-bank'
    | '/lessons/what-is-inflation'
    | '/lessons/where-money-comes-from'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/lessons'
    | '/notebook'
    | '/parents'
    | '/privacy'
    | '/safety'
    | '/terms'
    | '/dashboard/child'
    | '/dashboard/parent'
    | '/lessons/budgeting-like-a-boss'
    | '/lessons/compound-interest'
    | '/lessons/counting-coins'
    | '/lessons/earning-beyond-pocket-money'
    | '/lessons/needs-vs-wants'
    | '/lessons/piggy-bank-magic'
    | '/lessons/purpose-of-money'
    | '/lessons/sharing-giving'
    | '/lessons/smart-online-spending'
    | '/lessons/stocks-made-simple'
    | '/lessons/what-is-a-bank'
    | '/lessons/what-is-inflation'
    | '/lessons/where-money-comes-from'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/lessons'
    | '/notebook'
    | '/parents'
    | '/privacy'
    | '/safety'
    | '/terms'
    | '/dashboard/child'
    | '/dashboard/parent'
    | '/lessons/budgeting-like-a-boss'
    | '/lessons/compound-interest'
    | '/lessons/counting-coins'
    | '/lessons/earning-beyond-pocket-money'
    | '/lessons/needs-vs-wants'
    | '/lessons/piggy-bank-magic'
    | '/lessons/purpose-of-money'
    | '/lessons/sharing-giving'
    | '/lessons/smart-online-spending'
    | '/lessons/stocks-made-simple'
    | '/lessons/what-is-a-bank'
    | '/lessons/what-is-inflation'
    | '/lessons/where-money-comes-from'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  LessonsRoute: typeof LessonsRouteWithChildren
  NotebookRoute: typeof NotebookRoute
  ParentsRoute: typeof ParentsRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  TermsRoute: typeof TermsRoute
  DashboardChildRoute: typeof DashboardChildRoute
  DashboardParentRoute: typeof DashboardParentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/where-money-comes-from': {
      id: '/lessons/where-money-comes-from'
      path: '/where-money-comes-from'
      fullPath: '/lessons/where-money-comes-from'
      preLoaderRoute: typeof LessonsWhereMoneyComesFromRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/what-is-inflation': {
      id: '/lessons/what-is-inflation'
      path: '/what-is-inflation'
      fullPath: '/lessons/what-is-inflation'
      preLoaderRoute: typeof LessonsWhatIsInflationRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/what-is-a-bank': {
      id: '/lessons/what-is-a-bank'
      path: '/what-is-a-bank'
      fullPath: '/lessons/what-is-a-bank'
      preLoaderRoute: typeof LessonsWhatIsABankRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/stocks-made-simple': {
      id: '/lessons/stocks-made-simple'
      path: '/stocks-made-simple'
      fullPath: '/lessons/stocks-made-simple'
      preLoaderRoute: typeof LessonsStocksMadeSimpleRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/smart-online-spending': {
      id: '/lessons/smart-online-spending'
      path: '/smart-online-spending'
      fullPath: '/lessons/smart-online-spending'
      preLoaderRoute: typeof LessonsSmartOnlineSpendingRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/sharing-giving': {
      id: '/lessons/sharing-giving'
      path: '/sharing-giving'
      fullPath: '/lessons/sharing-giving'
      preLoaderRoute: typeof LessonsSharingGivingRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/purpose-of-money': {
      id: '/lessons/purpose-of-money'
      path: '/purpose-of-money'
      fullPath: '/lessons/purpose-of-money'
      preLoaderRoute: typeof LessonsPurposeOfMoneyRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/piggy-bank-magic': {
      id: '/lessons/piggy-bank-magic'
      path: '/piggy-bank-magic'
      fullPath: '/lessons/piggy-bank-magic'
      preLoaderRoute: typeof LessonsPiggyBankMagicRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/needs-vs-wants': {
      id: '/lessons/needs-vs-wants'
      path: '/needs-vs-wants'
      fullPath: '/lessons/needs-vs-wants'
      preLoaderRoute: typeof LessonsNeedsVsWantsRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/earning-beyond-pocket-money': {
      id: '/lessons/earning-beyond-pocket-money'
      path: '/earning-beyond-pocket-money'
      fullPath: '/lessons/earning-beyond-pocket-money'
      preLoaderRoute: typeof LessonsEarningBeyondPocketMoneyRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/counting-coins': {
      id: '/lessons/counting-coins'
      path: '/counting-coins'
      fullPath: '/lessons/counting-coins'
      preLoaderRoute: typeof LessonsCountingCoinsRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/compound-interest': {
      id: '/lessons/compound-interest'
      path: '/compound-interest'
      fullPath: '/lessons/compound-interest'
      preLoaderRoute: typeof LessonsCompoundInterestRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/lessons/budgeting-like-a-boss': {
      id: '/lessons/budgeting-like-a-boss'
      path: '/budgeting-like-a-boss'
      fullPath: '/lessons/budgeting-like-a-boss'
      preLoaderRoute: typeof LessonsBudgetingLikeABossRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/dashboard/parent': {
      id: '/dashboard/parent'
      path: '/dashboard/parent'
      fullPath: '/dashboard/parent'
      preLoaderRoute: typeof DashboardParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/child': {
      id: '/dashboard/child'
      path: '/dashboard/child'
      fullPath: '/dashboard/child'
      preLoaderRoute: typeof DashboardChildRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LessonsRouteChildren {
  LessonsBudgetingLikeABossRoute: typeof LessonsBudgetingLikeABossRoute
  LessonsCompoundInterestRoute: typeof LessonsCompoundInterestRoute
  LessonsCountingCoinsRoute: typeof LessonsCountingCoinsRoute
  LessonsEarningBeyondPocketMoneyRoute: typeof LessonsEarningBeyondPocketMoneyRoute
  LessonsNeedsVsWantsRoute: typeof LessonsNeedsVsWantsRoute
  LessonsPiggyBankMagicRoute: typeof LessonsPiggyBankMagicRoute
  LessonsPurposeOfMoneyRoute: typeof LessonsPurposeOfMoneyRoute
  LessonsSharingGivingRoute: typeof LessonsSharingGivingRoute
  LessonsSmartOnlineSpendingRoute: typeof LessonsSmartOnlineSpendingRoute
  LessonsStocksMadeSimpleRoute: typeof LessonsStocksMadeSimpleRoute
  LessonsWhatIsABankRoute: typeof LessonsWhatIsABankRoute
  LessonsWhatIsInflationRoute: typeof LessonsWhatIsInflationRoute
  LessonsWhereMoneyComesFromRoute: typeof LessonsWhereMoneyComesFromRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsBudgetingLikeABossRoute: LessonsBudgetingLikeABossRoute,
  LessonsCompoundInterestRoute: LessonsCompoundInterestRoute,
  LessonsCountingCoinsRoute: LessonsCountingCoinsRoute,
  LessonsEarningBeyondPocketMoneyRoute: LessonsEarningBeyondPocketMoneyRoute,
  LessonsNeedsVsWantsRoute: LessonsNeedsVsWantsRoute,
  LessonsPiggyBankMagicRoute: LessonsPiggyBankMagicRoute,
  LessonsPurposeOfMoneyRoute: LessonsPurposeOfMoneyRoute,
  LessonsSharingGivingRoute: LessonsSharingGivingRoute,
  LessonsSmartOnlineSpendingRoute: LessonsSmartOnlineSpendingRoute,
  LessonsStocksMadeSimpleRoute: LessonsStocksMadeSimpleRoute,
  LessonsWhatIsABankRoute: LessonsWhatIsABankRoute,
  LessonsWhatIsInflationRoute: LessonsWhatIsInflationRoute,
  LessonsWhereMoneyComesFromRoute: LessonsWhereMoneyComesFromRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  LessonsRoute: LessonsRouteWithChildren,
  NotebookRoute: NotebookRoute,
  ParentsRoute: ParentsRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  TermsRoute: TermsRoute,
  DashboardChildRoute: DashboardChildRoute,
  DashboardParentRoute: DashboardParentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
